name: Robbie Halleen
favicon: null
layout_spectrum: 0.356069763423875
typography_spectrum: 0.8440642359200865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.41276743658818305
  lightness: 0.39422917924821377
  saturation: 0.009688385995104909
  rhythmicContrast: 0.5319888924714178
purpose: []
